declare module 'request';

export declare type PhemexRequestOptions = {
    isLivenet: boolean,
    apiKey: string,
    secret: string
}

export declare type PhemexAccountInfo = {
    account: {
        userID: 905717,
        accountId: 9057170001,
        currency: string,
        accountBalanceEv: 35253484,
        totalUsedBalanceEv: 42189,
        bonusBalanceEv: 0
    },
    positions: PhemexAccountPosition[]
}

export declare type PhemexAccountPosition = {
    userID: number,
    accountID: number,
    symbol: string,
    currency: string,
    side: 'Buy' | 'Sell',
    positionStatus: Normal,
    crossMargin: false,
    leverageEr: number,
    leverage: number,
    initMarginReqEr: number,
    initMarginReq: number,
    maintMarginReqEr: number,
    maintMarginReq: number,
    riskLimitEv: number,
    riskLimit: number,
    size: number,
    value: number,
    valueEv: number,
    avgEntryPriceEp: number,
    avgEntryPrice: number,
    posCostEv: number,
    posCost: number,
    assignedPosBalanceEv: number,
    assignedPosBalance: number,
    bankruptCommEv: number,
    bankruptComm: number,
    bankruptPriceEp: number,
    bankruptPrice: number,
    positionMarginEv: number,
    positionMargin: number,
    liquidationPriceEp: number,
    liquidationPrice: number,
    deleveragePercentileEr: number,
    deleveragePercentile: number,
    buyValueToCostEr: number,
    buyValueToCost: number,
    sellValueToCostEr: number,
    sellValueToCost: number,
    markPriceEp: number,
    markPrice: number,
    markValueEv: number,
    markValue: null,
    unRealisedPosLossEv: number,
    unRealisedPosLoss: null,
    estimatedOrdLossEv: number,
    estimatedOrdLoss: number,
    usedBalanceEv: number,
    usedBalance: number,
    takeProfitEp: number,
    takeProfit: null,
    stopLossEp: number,
    stopLoss: null,
    cumClosedPnlEv: number,
    cumFundingFeeEv: number,
    cumTransactFeeEv: number,
    realisedPnlEv: number,
    realisedPnl: null | number,
    cumRealisedPnlEv: number,
    cumRealisedPnl: null | number,
    transactTimeNs: number,
    takerFeeRateEr: number,
    makerFeeRateEr: number,
    term: number,
    lastTermEndTimeNs: number,
    lastFundingTimeNs: number,
    curTermRealisedPnlEv: number,
    execSeq: number
}

export declare type PhemexOpenOrder = {
    bizError: number,
    orderID: string,
    clOrdID: string,
    symbol: string,
    side: 'Buy' | 'Sell',
    actionTimeNs: number,
    transactTimeNs: number,
    orderType: 'Limit' | 'Stop',
    priceEp: number,
    price: number,
    orderQty: number,
    displayQty: number,
    timeInForce: string,
    reduceOnly: false,
    closedPnlEv: number,
    closedPnl: number,
    closedSize: number,
    cumQty: number,
    cumValueEv: number,
    cumValue: number,
    leavesQty: number,
    leavesValueEv: number,
    leavesValue: number,
    stopDirection: string,
    stopPxEp: number,
    stopPx: number,
    trigger: string,
    pegOffsetValueEp: number,
    execStatus: string,
    pegPriceType: string,
    ordStatus: string
}